// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { FooDB } from '../foo-db'
import { FooService } from '../foo.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-foostable',
  templateUrl: './foos-table.component.html',
  styleUrls: ['./foos-table.component.css'],
})
export class FoosTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of Foo instances
  selection: SelectionModel<FooDB>;
  initialSelection = new Array<FooDB>();

  // the data source for the table
  foos: FooDB[];
  matTableDataSource: MatTableDataSource<FooDB>

  // front repo, that will be referenced by this.foos
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (fooDB: FooDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Name':
          return fooDB.Name;

        default:
          return FooDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (fooDB: FooDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the fooDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += fooDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private fooService: FooService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of foo instances
    public dialogRef: MatDialogRef<FoosTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.fooService.FooServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getFoos()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
      ]
      this.selection = new SelectionModel<FooDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getFoos()
    this.matTableDataSource = new MatTableDataSource(this.foos)
  }

  getFoos(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.foos = this.frontRepo.Foos_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.foos.forEach(
            foo => {
              let ID = this.dialogData.ID
              let revPointer = foo[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(foo)
              }
            }
          )
          this.selection = new SelectionModel<FooDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let foo = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(foo)
            }
          }
          this.selection = new SelectionModel<FooDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.foos
      }
    )
  }

  // newFoo initiate a new foo
  // create a new Foo objet
  newFoo() {
  }

  deleteFoo(fooID: number, foo: FooDB) {
    // list of foos is truncated of foo before the delete
    this.foos = this.foos.filter(h => h !== foo);

    this.fooService.deleteFoo(fooID).subscribe(
      foo => {
        this.fooService.FooServiceChanged.next("delete")
      }
    );
  }

  editFoo(fooID: number, foo: FooDB) {

  }

  // display foo in router
  displayFooInRouter(fooID: number) {
    this.router.navigate(["github_com_fullstack_lang_injectissue_stack1_go-" + "foo-display", fooID])
  }

  // set editor outlet
  setEditorRouterOutlet(fooID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_injectissue_stack1_go_editor: ["github_com_fullstack_lang_injectissue_stack1_go-" + "foo-detail", fooID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(fooID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_injectissue_stack1_go_presentation: ["github_com_fullstack_lang_injectissue_stack1_go-" + "foo-presentation", fooID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.foos.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.foos.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<FooDB>()

      // reset all initial selection of foo that belong to foo
      this.initialSelection.forEach(
        foo => {
          foo[this.dialogData.ReversePointer].Int64 = 0
          foo[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(foo)
        }
      )

      // from selection, set foo that belong to foo
      this.selection.selected.forEach(
        foo => {
          let ID = +this.dialogData.ID
          foo[this.dialogData.ReversePointer].Int64 = ID
          foo[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(foo)
        }
      )

      // update all foo (only update selection & initial selection)
      toUpdate.forEach(
        foo => {
          this.fooService.updateFoo(foo)
            .subscribe(foo => {
              this.fooService.FooServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedFoo = new Set<number>()
      for (let foo of this.initialSelection) {
        if (this.selection.selected.includes(foo)) {
          // console.log("foo " + foo.Name + " is still selected")
        } else {
          console.log("foo " + foo.Name + " has been unselected")
          unselectedFoo.add(foo.ID)
          console.log("is unselected " + unselectedFoo.has(foo.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let foo = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedFoo.has(foo.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          foo => {
            if (!this.initialSelection.includes(foo)) {
              // console.log("foo " + foo.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + foo.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = foo.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("foo " + foo.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<FooDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
