// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { FooAPI } from './foo-api';
import { FooDB } from './foo-db';

@Injectable({
  providedIn: 'root'
})
export class FooService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  FooServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private foosUrl = 'http://localhost:8080/api/github.com/fullstack-lang/injectissue/stack1/go/v1/foos';

  constructor(
    private http: HttpClient
  ) { }

  /** GET foos from the server */
  getFoos(): Observable<FooDB[]> {
    return this.http.get<FooDB[]>(this.foosUrl)
      .pipe(
        tap(_ => this.log('fetched foos')),
        catchError(this.handleError<FooDB[]>('getFoos', []))
      );
  }

  /** GET foo by id. Will 404 if id not found */
  getFoo(id: number): Observable<FooDB> {
    const url = `${this.foosUrl}/${id}`;
    return this.http.get<FooDB>(url).pipe(
      tap(_ => this.log(`fetched foo id=${id}`)),
      catchError(this.handleError<FooDB>(`getFoo id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new foo to the server */
  postFoo(foodb: FooDB): Observable<FooDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

		return this.http.post<FooDB>(this.foosUrl, foodb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted foodb id=${foodb.ID}`)
			}),
			catchError(this.handleError<FooDB>('postFoo'))
		);
  }

  /** DELETE: delete the foodb from the server */
  deleteFoo(foodb: FooDB | number): Observable<FooDB> {
    const id = typeof foodb === 'number' ? foodb : foodb.ID;
    const url = `${this.foosUrl}/${id}`;

    return this.http.delete<FooDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted foodb id=${id}`)),
      catchError(this.handleError<FooDB>('deleteFoo'))
    );
  }

  /** PUT: update the foodb on the server */
  updateFoo(foodb: FooDB): Observable<FooDB> {
    const id = typeof foodb === 'number' ? foodb : foodb.ID;
    const url = `${this.foosUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put(url, foodb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated foodb id=${foodb.ID}`)
      }),
      catchError(this.handleError<FooDB>('updateFoo'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
